# Generated by Django 4.1.1 on 2022-09-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='btn',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
