# Generated by Django 4.1.1 on 2022-09-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_title_btn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abaout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='abaut page', max_length=30)),
                ('text', models.CharField(default='your text here', max_length=300)),
                ('btn', models.CharField(default='click here', max_length=20)),
            ],
        ),
    ]
