# Generated by Django 4.1.1 on 2022-09-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_abaout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
