# Generated by Django 4.1.1 on 2022-09-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0005_expertises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=70)),
            ],
        ),
    ]
