# Generated by Django 4.1.1 on 2022-09-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0006_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('develop', models.CharField(max_length=70)),
            ],
        ),
    ]
